### ISSUE TITLE
安装容器的时候里面tigervnc的链接失效了

### ISSUE THREAD

**Issue by zhougy1989** [vmware/test-automation-for-web-applications#1]
### Describe the bug

脚本：tigervnc.sh中使用的包链接https://github.com/accetto/tigervnc/releases/download/v1.8.0-mirror/tigervnc-1.8.0.x86_64.tar.gz已经失效，导致build失败

### Reproduction steps

1.
2.
3.
...
无

### Expected behavior

build失败

**Comment by zhougy1989** [comment]
我换了一个链接后，vncpasswd: command not found ,启动镜像会有这个报错，能问下是什么情况么
![image](https://github.com/vmware/test-automation-for-web-applications/assets/50607317/64086eef-9f37-4fb4-87b5-ded2c48ce94b)


@zhenjunz

**Comment by zhenjunz** [comment]
@zhougy1989 还是vncserver没有安装成功， 你可以改成下面的链接：
https://github.com/neoavalon/docker-ros-elg5228_ext/raw/master/lib/tigervnc-1.8.0.x86_64.tar.gz

**Comment by zhenjunz** [comment]
close it.
